
CREATE COLUMN TABLE "SURVEY_SCHEMA"."QUESTIONS" ("ID" NVARCHAR(36) DEFAULT SYSUUID NOT NULL ,
"SURVEY_ID" NVARCHAR(36) NOT NULL ,
"QUESTION_TEXT" NCLOB MEMORY THRESHOLD 1000 NOT NULL ,
"QUESTION_TYPE" NVARCHAR(20) NOT NULL ,
"OPTIONS" NCLOB MEMORY THRESHOLD 1000,
"IS_REQUIRED" TINYINT DEFAULT 0 NOT NULL ,
"QUESTION_ORDER" INTEGER,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "SURVEY_SCHEMA"."QUESTIONS" WITH PARAMETERS ('CONCAT_ATTRIBUTE' =('$SURVEY_ID$QUESTION_ORDER$',
'SURVEY_ID',
'QUESTION_ORDER'));

CREATE CPBTREE INDEX "IDX_QUESTIONS_SURVEY_ID" ON
"SURVEY_SCHEMA"."QUESTIONS" ( "SURVEY_ID" ASC );

CREATE CPBTREE INDEX "IDX_QUESTIONS_ORDER" ON
"SURVEY_SCHEMA"."QUESTIONS" ( "SURVEY_ID" ASC,
"QUESTION_ORDER" ASC );

ALTER TABLE "SURVEY_SCHEMA"."QUESTIONS" ADD FOREIGN KEY ("SURVEY_ID") REFERENCES "SURVEY_SCHEMA"."SURVEYS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    CASCADE ENFORCED VALIDATED INITIALLY IMMEDIATE;
    
    -- SURVEY_SCHEMA.RESPONSES definition
    
    CREATE COLUMN TABLE "SURVEY_SCHEMA"."RESPONSES" ("ID" NVARCHAR(36) DEFAULT SYSUUID NOT NULL ,
    "ASSIGNMENT_ID" NVARCHAR(36) NOT NULL ,
    "QUESTION_ID" NVARCHAR(36) NOT NULL ,
    "RESPONSE_TEXT" NCLOB MEMORY THRESHOLD 1000,
    "SUBMITTED_AT" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    "IS_APPROVED" TINYINT DEFAULT 0 NOT NULL ,
    "APPROVED_BY" NVARCHAR(36),
    "APPROVED_AT" LONGDATE,
    PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;
    
    CREATE CPBTREE INDEX "IDX_RESPONSES_ASSIGNMENT_ID" ON
    "SURVEY_SCHEMA"."RESPONSES" ( "ASSIGNMENT_ID" ASC );
    
    CREATE CPBTREE INDEX "IDX_RESPONSES_QUESTION_ID" ON
    "SURVEY_SCHEMA"."RESPONSES" ( "QUESTION_ID" ASC );
    
    CREATE CPBTREE INDEX "IDX_RESPONSES_APPROVED" ON
    "SURVEY_SCHEMA"."RESPONSES" ( "IS_APPROVED" ASC );
    
    CREATE UNIQUE INVERTED INDIVIDUAL INDEX "IDX_UNIQUE_RESPONSE" ON
    "SURVEY_SCHEMA"."RESPONSES" ( "ASSIGNMENT_ID",
    "QUESTION_ID" );
    
    ALTER TABLE "SURVEY_SCHEMA"."RESPONSES" ADD FOREIGN KEY ("ASSIGNMENT_ID") REFERENCES "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
        CASCADE ENFORCED VALIDATED INITIALLY IMMEDIATE;
    
    ALTER TABLE "SURVEY_SCHEMA"."RESPONSES" ADD FOREIGN KEY ("QUESTION_ID") REFERENCES "SURVEY_SCHEMA"."QUESTIONS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
        RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
    
    ALTER TABLE "SURVEY_SCHEMA"."RESPONSES" ADD FOREIGN KEY ("APPROVED_BY") REFERENCES "SURVEY_SCHEMA"."USERS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
    
    -- SURVEY_SCHEMA.SURVEY_ASSIGNMENTS definition
    
    CREATE COLUMN TABLE "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ("ID" NVARCHAR(36) DEFAULT SYSUUID NOT NULL ,
    "SURVEY_ID" NVARCHAR(36) NOT NULL ,
    "CUSTOMER_ID" NVARCHAR(36) NOT NULL ,
    "ASSIGNED_BY" NVARCHAR(36) NOT NULL ,
    "ASSIGNED_AT" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    "STATUS" NVARCHAR(20) DEFAULT 'ASSIGNED' NOT NULL ,
    "QUARTER" NVARCHAR(10),
    "DUE_DATE" DATE,
    PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;
    
    CREATE UNIQUE INVERTED INDIVIDUAL INDEX "IDX_UNIQUE_ASSIGNMENT" ON
    "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ( "SURVEY_ID",
    "CUSTOMER_ID",
    "QUARTER" );
    
    CREATE CPBTREE INDEX "IDX_ASSIGNMENTS_SURVEY_ID" ON
    "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ( "SURVEY_ID" ASC );
    
    CREATE CPBTREE INDEX "IDX_ASSIGNMENTS_CUSTOMER_ID" ON
    "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ( "CUSTOMER_ID" ASC );
    
    CREATE CPBTREE INDEX "IDX_ASSIGNMENTS_STATUS" ON
    "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ( "STATUS" ASC );
    
    ALTER TABLE "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ADD FOREIGN KEY ("SURVEY_ID") REFERENCES "SURVEY_SCHEMA"."SURVEYS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
        RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
    
    ALTER TABLE "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ADD FOREIGN KEY ("CUSTOMER_ID") REFERENCES "SURVEY_SCHEMA"."USERS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
        RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
    
    ALTER TABLE "SURVEY_SCHEMA"."SURVEY_ASSIGNMENTS" ADD FOREIGN KEY ("ASSIGNED_BY") REFERENCES "SURVEY_SCHEMA"."USERS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
    -- SURVEY_SCHEMA.SURVEYS definition
    
    CREATE COLUMN TABLE "SURVEY_SCHEMA"."SURVEYS" ("ID" NVARCHAR(36) DEFAULT SYSUUID NOT NULL ,
    "TITLE" NVARCHAR(200) NOT NULL ,
    "DESCRIPTION" NCLOB MEMORY THRESHOLD 1000,
    "CREATED_BY" NVARCHAR(36),
    "IS_ACTIVE" TINYINT DEFAULT 1 NOT NULL ,
    "CREATED_AT" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;
    
    CREATE CPBTREE INDEX "IDX_SURVEYS_CREATED_BY" ON
    "SURVEY_SCHEMA"."SURVEYS" ( "CREATED_BY" ASC );
    
    ALTER TABLE "SURVEY_SCHEMA"."SURVEYS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SURVEY_SCHEMA"."USERS" ("ID") ON
    UPDATE
        RESTRICT ON
        DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;
    -- SURVEY_SCHEMA.USERS definition
    
    CREATE COLUMN TABLE "SURVEY_SCHEMA"."USERS" ("ID" NVARCHAR(36) DEFAULT SYSUUID NOT NULL ,
    "USERNAME" NVARCHAR(50) NOT NULL ,
    "PASSWORD_HASH" NVARCHAR(255) NOT NULL ,
    "EMAIL" NVARCHAR(100) NOT NULL ,
    "ROLE" NVARCHAR(20) NOT NULL ,
    "CREATED_AT" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    PRIMARY KEY ("ID"),
UNIQUE CPBTREE ("USERNAME")) UNLOAD PRIORITY 5 AUTO MERGE;
    
    